# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c6ed84b673598d763e101a2aab73f4c62d80097b414837138f8933721d5aa23b940ba58270351669f34382abe2110a26bd9910835123364d267637c9d2d847b

test:
  secret_key_base: a055c2ddb3526584c59d762f42b1413a24a3739ce5b976b1090810557aa6cb6ec327b37af5918d0c515a7c644f014a6cef8778a2dfc9a0477012368fdcd76150

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
